version: '3.8'

services:
  aseprite-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: aseprite-mcp:latest
    container_name: aseprite-mcp-server
    restart: unless-stopped
    # Uncomment the following line if you need to expose ports
    # ports:
    #   - "8080:8080"
    
    # Mount volumes for development
    volumes:
      - .:/app
    
    # Environment variables (copy from sample.env if needed)
    # env_file:
    #   - .env
    
    # Override entrypoint for development
    # entrypoint: ["tail", "-f", "/dev/null"]
    
    # For production, use the default entrypoint
    stdin_open: true
    tty: true

  # Optional: Add a development service
  aseprite-mcp-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: aseprite-mcp:latest
    container_name: aseprite-mcp-dev
    volumes:
      - .:/app
    entrypoint: ["tail", "-f", "/dev/null"]
    stdin_open: true
    tty: true
    profiles:
      - dev
